### PR TITLE
2 include new sampled data example

### PR DESCRIPTION
**Pull request by jakobdambon**
Using the `spam::rmvnorm` suite to sample SVC data, therefore replacing the old functions depending on package `RandomFields`. 

Main changes: 

- package contains a new sample data set called `SVCdata`, that has been sample from the `RandomFields` package. In the help file, I cite the RandomFields JSS article to give them the appropriate credit.
- package contains one sample function called `sample_SVCdata`.

### CODE REVIEW

**Comment by reinhardfurrer** [comment]
I had a quick look. seems reasonable. I will have a closer, detailed look once I am back in CH.

----- Original Message -----
> From: "Jakob Dambon" ***@***.***>
> To: "jakobdambon/varycoef" ***@***.***>
> Cc: "reinhard" ***@***.***>, "Review requested" ***@***.***>
> Sent: Tuesday, 7 June, 2022 23:23:56
> Subject: Re: [jakobdambon/varycoef] 2 include new sampled data example (PR #4)

> @jakobdambon requested your review on: jakobdambon/varycoef#4 2 include new
> sampled data example.
> 
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/jakobdambon/varycoef/pull/4#event-6764841242
> You are receiving this because your review was requested.
> 
> Message ID: ***@***.***>

-- 
______________________________________________________________________
University of Zurich                ***@***.***
Department of Mathematics                         tel: +41-44-63-55843
   and Institute of Computational Science              office: Y27 J34
CH-8057 Zurich                          https://www.math.uzh.ch/furrer
                                    https://twitter.com/ReinhardFurrer

**Comment by reinhardfurrer** [comment]
Good to go. 2 cents:

For `sample_SVCdata()` should there be an  'X=NULL` argument? 
I tried to construct a nice figure (one-dim domain) to illustrate the additiveness of the SVC but with a `rnorm()` noise, one hardly sees anything. 

Would it make sense to include the wrapper functions `cov.mat32` and `cov.mat52()` in `spam`? 
With these wrappers, you could simply construct a `do.call()` with any covariance function based on 3 parameters. Mainly aesthetics...

**Comment by jakobdambon** [comment]
I've added the `X=NULL` argument and pushed into master.

I don't understand your comment on the example / figure / additiveness of the SVCs. For a nice example, I use a code like this:

```
set.seed(123)
# SVC parameters
(df.pars <- data.frame(
   var = c(2, 1),
   scale = c(3, 1),
   mean = c(1, 2)))
# nugget standard deviation
tau <- 0.5

# sample locations
s <- sort(runif(500, min = 0, max = 10))
SVCdata <- sample_SVCdata(
  df.pars = df.pars, nugget.sd = tau, locs = s, cov.name = "mat32"
)

matplot(x = SVCdata$locs, y = SVCdata$beta, type = "l")
```
Could you provide an example?


For your final comment, I will put it in a backlog.

**Comment by reinhardfurrer** [comment]
I was thinking of:
```
# sample locations
s <- sort(runif(100, min = 0, max = 10))
X <- cbind(1, rep(c(0, 1, .5, 0, 1), times=c(24, 35, 5, 12, 24)))
SVCdata <- sample_SVCdata(
  df.pars = df.pars, nugget.sd = tau, locs = s, cov.name = "mat32", X = X
)
with(data = SVCdata, {
  plot( s, y, ylim = c(-1,6))
  lines(s, rowSums(X * beta), col = 2)
  lines(s, beta[,1], col = 3)
  lines(s, beta[,2], col = 4)
  lines(s, X[,2], col = 5)
})
legend("topright", legend = c('smooth fit', "first SVC", "second SVC", 
  "covariate second SVC"), col=c(2:5), bty = 'n', lty = 1)
```
It was helpful to understand the role of the covariate. I struggle with random covariates. Just a tiny detail, nothing to worry.

**Pull request merged**
